var language = ""; // (french/Italian/portuguese) Leave blank for English
var defaultPage = "1"; // Changes default launch page (1=Weather/Date/Time) (2=Music Player) (3=Device Info) (4=Countdown)
var pageSwitch = true; // Enables/Disables tapping to switch page
var clock = false; // Enables 24hour clock
var seconds = true; // shows seconds
var dayMonth = false; // Places day of month before name of month
var LightBackground = true; // Enables a light theme
var customBackgroundColor = false; 
var customColor = "blue"; 
var image = ""; // Url to background image
var opacity = "0.1"; 
var CustomTextColor = false; 
var PickColor = "black"; // Pick a custom color (Type a color name or a hex code)(Overides DarkText/LightText)
var feelsLike = true; 
var musicApp = "com.netease.cloudmusic"; 
var showArt = false; // Hides/shows album art
var backgroundArt = true; // Makes the widget background the album art (BETA)
var artBorder = false; // Adds border to album art
var borderWidth = "2"; // Width of the border around album art in px
var borderColor = "white"; 
var stockIcons = true; // Uses stock iOS media controls
var infoAlign = "center"; // Text position for device info page (left/right/center)
var countdown = true; // Hide/Show countdown page
var countMonth = "Oct"; // Abreviated month you are counting down to
var countDay = "18"; // Day you are counting down to
var countYear = "2019"; // Year you are counting down to
var countHour = "0"; // Hour you are counting down to (24hour)(optional)
var countMinute = "1"; // Minute you are counting down to (required)
var eventName = "License"; // Replaces date on countdown leave black to show date
var refresh = "30000"; // Refreshes widget and returns it to default page after this many seconds (Add 000 after the amount of seconds)
